// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PDFService is an autogenerated mock type for the PDFService type
type PDFService struct {
	mock.Mock
}

// CreateJob provides a mock function with given fields: ctx, r, size
func (_m *PDFService) CreateJob(ctx context.Context, r io.Reader, size int64) (uuid.UUID, error) {
	ret := _m.Called(ctx, r, size)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, int64) (uuid.UUID, error)); ok {
		return rf(ctx, r, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, int64) uuid.UUID); ok {
		r0 = rf(ctx, r, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, int64) error); ok {
		r1 = rf(ctx, r, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPDFService creates a new instance of PDFService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPDFService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PDFService {
	mock := &PDFService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
