// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobStage string

const (
	JobStageUploaded    JobStage = "uploaded"
	JobStageParsing     JobStage = "parsing"
	JobStageParsed      JobStage = "parsed"
	JobStageCleaning    JobStage = "cleaning"
	JobStageCleaned     JobStage = "cleaned"
	JobStageChunking    JobStage = "chunking"
	JobStageChunked     JobStage = "chunked"
	JobStageSummarizing JobStage = "summarizing"
	JobStageSummarized  JobStage = "summarized"
	JobStageAggregating JobStage = "aggregating"
	JobStageCompleted   JobStage = "completed"
)

func (e *JobStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStage(s)
	case string:
		*e = JobStage(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStage: %T", src)
	}
	return nil
}

type NullJobStage struct {
	JobStage JobStage
	Valid    bool // Valid is true if JobStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStage) Scan(value interface{}) error {
	if value == nil {
		ns.JobStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStage), nil
}

type ParsingErrorType string

const (
	ParsingErrorTypeOpen            ParsingErrorType = "open"
	ParsingErrorTypeCorrupted       ParsingErrorType = "corrupted"
	ParsingErrorTypeEncrypted       ParsingErrorType = "encrypted"
	ParsingErrorTypeTimeout         ParsingErrorType = "timeout"
	ParsingErrorTypeExtract         ParsingErrorType = "extract"
	ParsingErrorTypeStorageDownload ParsingErrorType = "storage_download"
	ParsingErrorTypeStorageUpload   ParsingErrorType = "storage_upload"
	ParsingErrorTypeDb              ParsingErrorType = "db"
	ParsingErrorTypeUnknown         ParsingErrorType = "unknown"
)

func (e *ParsingErrorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParsingErrorType(s)
	case string:
		*e = ParsingErrorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ParsingErrorType: %T", src)
	}
	return nil
}

type NullParsingErrorType struct {
	ParsingErrorType ParsingErrorType
	Valid            bool // Valid is true if ParsingErrorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParsingErrorType) Scan(value interface{}) error {
	if value == nil {
		ns.ParsingErrorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParsingErrorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParsingErrorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParsingErrorType), nil
}

type WorkStatus string

const (
	WorkStatusPending    WorkStatus = "pending"
	WorkStatusProcessing WorkStatus = "processing"
	WorkStatusCompleted  WorkStatus = "completed"
	WorkStatusFailed     WorkStatus = "failed"
)

func (e *WorkStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkStatus(s)
	case string:
		*e = WorkStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkStatus: %T", src)
	}
	return nil
}

type NullWorkStatus struct {
	WorkStatus WorkStatus
	Valid      bool // Valid is true if WorkStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkStatus), nil
}

type ChunkTask struct {
	ID         pgtype.UUID
	JobID      pgtype.UUID
	ChunkIndex int32
	Status     WorkStatus
	Attempts   int32
	ChunkKey   string
	ResultKey  pgtype.Text
	Error      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Job struct {
	ID             pgtype.UUID
	Stage          JobStage
	Status         WorkStatus
	ObjectKey      string
	Attempts       int32
	TextKey        pgtype.Text
	CleanedTextKey pgtype.Text
	SummaryKey     pgtype.Text
	Error          pgtype.Text
	ErrorType      NullParsingErrorType
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
